version: '3'
services:
  poet-mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
  poet-rabbit:
    image: rabbitmq:3
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    hostname: my-rabbit
  poet-ipfs:
    image: ipfs/go-ipfs:v0.4.17
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - .ipfs-docker:/data/ipfs
  poet-node:
    build: .
    ports:
      - "18080:18080"
    depends_on:
      - poet-mongo
      - poet-rabbit
      - poet-ipfs
    environment:
      - RABBITMQ_URL=amqp://poet-rabbit
      - MONGODB_URL=mongodb://poet-mongo:27017/poet
      - IPFS_URL=http://poet-ipfs:5001
    hostname: poet-node
    links:
      - poet-mongo
      - poet-rabbit
      - poet-ipfs
    command: >
      /bin/bash -c "
        sleep 10;
        npm start;
      "
  poet-bitcoind:
    image: ruimarinho/bitcoin-core:0.16.0
    volumes:
      - bitcoind1:/home/bitcoin/.bitcoin
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18444:18444"
    command:
      -printtoconsole
      -server
      -testnet=1
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0

volumes:
  bitcoind1:
    driver: local